/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    GradientBackground: typeof import('./components/background/GradientBackground.vue')['default']
    IEpDelete: typeof import('~icons/ep/delete')['default']
    IEpDownload: typeof import('~icons/ep/download')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpFolderAdd: typeof import('~icons/ep/folder-add')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    IEpQuestionFilled: typeof import('~icons/ep/question-filled')['default']
    IEpSetting: typeof import('~icons/ep/setting')['default']
    IEpUpload: typeof import('~icons/ep/upload')['default']
    Login: typeof import('./components/login/login.vue')['default']
    MainLabel: typeof import('./components/label/MainLabel.vue')['default']
    Register: typeof import('./components/login/register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
